#!/bin/bash
#
# APDATASET.DAYMD.SHOKYAKU_KANRI　(償却管理のPOMPA更新)
#
# Usage:APDATASET.DAYMD.SHOKYAKU_KANRI
#
# Written By Aoyagi (HandsLab .Inc) :
#

# 設定ファイ読込 #########################################################################
source /home/hands/.bashrc &> /dev/null

#--------------------ログ出力--------------------
mkdir -p /home/hands/E-LIFE/KEIRI/APLOG/$(date +%Y%m%d)
exec 2> /home/hands/E-LIFE/KEIRI/APLOG/$(date +%Y%m%d)/LOG.$(basename ${0}).${HOSTNAME}.$(date "+%Y%m%d"); set -xv

# エラー終了  ############################################################################
function error_exit {
  touch ${semaphore_dir}/$(basename ${0}).${HOSTNAME}.ERROR.${today}
  rm -f ${tmp}-*
  exit 1
}


#shisetsu=${1}
#month=${2}

# 変数・ディレクトリ設定 #################################################################
current_time="$(date "+%Y%m%d%H%M%S")"
yesterday=$(mdate $today/-1)
home_dir="/home/hands"
app_dir="${home_dir}/E-LIFE/KEIRI"
cgi_dir="${app_dir}/CGI"
html_dir="${app_dir}/HTML"
tbl_dir="${app_dir}/TBL"
input_dir="/home/hands/E-LIFE/UNEI/INPUT"
tmp="/var/tmp/${$}"
semaphore_dir="${home_dir}/SEMAPHORE"
meisai_dir="${app_dir}/MEISAI"
rireki_dir="${app_dir}/RIREKI"
kanri_dir="${app_dir}/KANRI"
pompa_dir="${app_dir}/POMPA/SHOKYAKU_KANRI"
work="${app_dir}/WORK"
riyosha_dir="/DATA/E-LIFE/UNEI/RIYOUSHA"
keiri_input="${app_dir}/INPUT"
meisai_dir="/DATA/E-LIFE/SEIKYU/SHISETSU/0001/MEISAI/"

# スタート日
shokaishokai=$(mdate 20141108/+30)
# 日割り金額
echo '70000' | lcalc '$1/30' |
lcalc '$1/2' |
marume +age 1.0              > $tmp-base_kingaku
kingaku=$(cat $tmp-base_kingaku)

for month in $(mdate -e 201412m/+2);do
  shonichi=$(echo ${month}"01")
  [ "${month}" = "201412" ] && shonichi=$shokaishokai
  lastday=$(mdate ${month}m | tarr | tail -n1)
  mdate ${lastday} ${shonichi} |
  lcalc '$1+1'                 > $tmp-nissu

  echo $kingaku    |
  cat $tmp-nissu - |
  lcalc '$1*$2'
done

# 日割りする金額




# 終了 ######################################################################
rm -f ${tmp}-*
exit 0

